[colors.bright]
black = "0x3B4252" # Polar Night 2
blue = "0x88C0D0"  # Frost 2
cyan = "0x8FBCBB"  # Frost 1
green = "0xA3BE8C" # Aurora Green
magenta = "0xB48EAD" # Aurora Purple
red = "0xBF616A"   # Aurora Red
white = "0xECEFF4" # Snow Storm 3
yellow = "0xEBCB8B"  # Aurora Yellow

[colors.normal]
black = "0x2E3440" # Polar Night 1
blue = "0x5E81AC"  # Frost 3
cyan = "0x8FBCBB"  # Frost 1
green = "0xA3BE8C" # Aurora Green
magenta = "0xB48EAD" # Aurora Purple
red = "0xBF616A"   # Aurora Red
white = "0xD8DEE9" # Snow Storm 1
yellow = "0xEBCB8B"  # Aurora Yellow

[colors.primary]
background = "0x2E3440" # Polar Night 1
foreground = "0xD8DEE9" # Snow Storm 1

[font]
size = 11.5

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[window]
opacity = 0.8
